name: Check Markdown links

on:
  workflow_run:
    workflows: ["Build Website"]
    types:
      - completed

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        file-extension: .md .mdx
